name: Unit test mobile
on:
  pull_request:
    branches:
      - develop
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          npm install
      - name: Test
        run: |
          npm run test:coverage
